[package]
name = "reth-lighthouse"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.4", features = ["full"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
eyre = "0.6.12"
